### ISSUE TITLE
Finish the covidcast_signals function

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#10]
It's currently in the R package, but not exported. Remaining issues:

* [x] How should the sources/signals be specified? Currently it accepts a data frame, but Ryan thinks separate vectors with recycling would be convenient, so you could specify things like `data_source = "jhu-csse"` , and `signal = c("confirmed_incidence_num", "confirmed_incidence_prop")`.
* [x] Should it be possible to select signals with different `geo_types` in one call?
* [x] How should `plot.covidcast_signal()` handle data frames containing multiple signals? It could make a grid of plots, perhaps; faceting doesn't work easily because different signals are on different scales.

I also think we should provide a convenience function that wraps `pivot_wider` to convert a data frame with multiple signals to have one row per date and one column per signal, named after the signal, instead of one row per observation per signal. People might like such a data frame (it'd be useful for making feature matrices for models).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970310857497) by [Unito](https://www.unito.io/learn-more)

**Comment by ryantibs** [comment]
@capnrefsmmat I'm going to dust off this one and revisit it now. Here's my plan: 

- Same argument structure as `covidcast_signal()`, and allow recycling for the first 4 arguments (`data_source`, `signal`, `start_day`, `end_day`).  For the rest, allow just one value.
- Don't allow multiple `geo_type`s (since you can only specify one value for that argument, as per my last comment).  Seems cleanest if we force them to make separate function calls.
- Currently, I would say, disable plotting.

And important difference is that I would have `covidcast_signals()` return a list.  I don't think a tall or wide data frame is the most natural thing to return at the outset.  I'd say return a list where each element is a `covidcast_signal` data frame, then provide the following utility functions:

- `aggregate_signals()`: this aggregates the signals stored in the list elements.
    * This function takes an argument `type` which can be one of "tall" or "wide".  If "tall", then it gives what your current `covidcast_signals()` function does; just binds all the rows together (and preserves the metadata).  If "wide", then it renames the `value` column according to the data source and signal.
    * This function also allows you to, simultaneously, add lags or leads of your variables, in either format: tall or wide.
- `covidcast_taller()`, `covidcast_wider()`: these are just wrapper around `pivot_taller()`, `pivot_wider()` to allow you to move back and forth between the two forms, with the proper translation between the data source and signal names, etc.

Note that tis would simultaneously address #48.  If you have concerns, lmk soon because I'll probably start on this soon!  cc @chinandrew

**Comment by capnrefsmmat** [comment]
I think this design makes sense, although the devil is in the details. (For example, what's the most natural way to specify lags for `aggregate_signals`?) Having convenient ways to produce wide data frames with lags  would be very useful for quick data analyses, though.

**Comment by ryantibs** [comment]
😈 🔢

**Comment by chinandrew** [comment]
> * Same argument structure as `covidcast_signal()`, and allow recycling for the first 4 arguments (`data_source`, `signal`, `start_day`, `end_day`).  For the rest, allow just one value.

- Just to clarify, if I specify `source=c('a','b')` and `signal=c('x','y')`, is the anticipated result an `a-x` df and a `b-y` df? (as opposed to their cartesian product `a-x`,`a-y`, `b-x`, and `b-y`.) Source/signal combinations probably make less sense since signals are often unique to sources, but you could run the same question with start days...though that also doesn't make a lot of sense since you could just request the largest range of days and slice down.
- Do the first four arguments have to have the same length? e.g. if i want 2 signals for one source, can i do `source='a'` and `signal=c('x','y')`, or do i need to provide `source=c('a','a')`? If we want to make it very explicit, it makes sense to mandate the input vectors have to be the same length, but I can also see an exception for single values (e.g. one source) for convenience.
- This may be a dumb question, but how critical is this functionality in the first place? If I want to get 5 signals and have the various sources and signals i want in mind, seems like the marginal cost of just calling `signal()` a few more times and appending to a list vs adding them as vectors to a new function is quite small, and then I pass that list to the utility functions.

> And important difference is that I would have `covidcast_signals()` return a list. I don't think a tall or wide data frame is the most natural thing to return at the outset. I'd say return a list where each element is a `covidcast_signal` data frame

This makes sense to me. As Alex and I discussed when implementing the aggregate signals function, it seems that currently a 'signal' is the unit of operation and multiple signals aren't anything unique warranting their own object i.e. theyre just a collection of signals as opposed to a special 'multi-signal'.

**Comment by ryantibs** [comment]
Hi @capnrefsmmat @chinandrew, I just pushed a branch "modeltools" that contains nearly all of the aggregation functionality implemented.  It's not 100% polished, but I need to move onto something else, so I figured I would at least ping you two so that if either of you have the cycles to look in the next couple days, you could go ahead and leave feedback while I'm iterating elsewhere. 

I didn't submit this branch as a draft PR because I branched it from evalcast-review, which is like millions of commits past main, which would result in one huge log to scroll through.  (And I didn't want to do a draft PR to evalcast-review or evalcast, because those will get merged by Jacob very soon, apparently).

Andrew: sorry for the short reply here but the answer to all of your questions lie in the design choices I made on the branch.  Looking at the file `vignettes/multi-signals.Rmd` will give you the best idea of how to use all of these functions.  And look at the notes on my last commit: I wrote down several thoughts about the design, including some concerns I have about it.

**Comment by chinandrew** [comment]
Took at look at the commit and the vignettes. I agree that the `append_shift` being wide and `aggregate_signals` being wide or long is a bit weird.

My take would be to remove the overlap between the responsibilities of the functions. Right now, both do some form of aggregation/appending (e.g. I can get a wide, lagged df on a signal by running either `append_shift` or by using `aggregate_signals` on a signal and a shifted copy of that signal that I make myself). Instead, how about making `append_shift` into something that doesn't append and just shifts, overwriting the original value and returning the same dimensions as the input df (or maybe returns a list of shifted dfs if you have multiple lags?). `aggregate_signals` still behaves as is. 

A second minor consideration in that world is whether `append_shift` needs to be public, as it could be called by `aggregate_signals` with the lag argument. Depends on if you believe `aggregate_signals` should have any concept of lags, or if it's naive to that and it's existence is just to smash dataframes together.

I'm not the most fluent with how R treats lists and how easy it is to manipulate/concatenate them, so may be off base here. Coming from the Python mindset, what I have in mind is you run something like the following (using python list notation):

e.g. if I want signal `a`, signal `a` lagged 7 days, signal `b`, and signal `c` lagged 14 days, I run either:

a) `aggregate_signals([a, a, b, c], dt=[0,7,0,14])` which is the current python implementation where `aggregate_signals` lags for you, or 
b) `aggregate_signals([a, shift(a,7), b, shift(c,14)])`  if you prefer `aggregate_signals` not handle lags.

**Comment by ryantibs** [comment]
Thanks @chinandrew, really helpful feedback!  I just revamped a bit and committed pushed to my branch.  Take a look.  The long form commit gives a detailed account of what I did.  Pasted here for convenience

```
    Revamp aggregate_signals() and related functions
    
    - Thanks to Andrew Chin for helpful feedback
    - Rename append_shifts() to apply_shifts(): now you have to ask
      for dt = 0 in order to retain the original value column, else it
      is dropped. This is cleaner behavior and leads to easier logic
      downstream
    - Hide apply_shifts() from the documentation. Remains in NAMESPACE
      so technically a user can call it but it's not visible. This is
      probably best as it presents a simpler set of options to the end
      user, and hides the overlap and somewhat ugly asymmetry between
      apply_shifts() and aggregate_signals()
    - Change aggregate_signals() so that it takes an argument dt to do
      shifts; clarify in the documentation the three main use cases
      for this function
    - Fix up covidcast_wider() and covidcast_taller(), and vignette
```

So it's consistent with your feedback, except I allow more flexibility in how the user specifies shifts.  Suppose I want to add 28 lags to `a` and append this to `b`.  Technically you can do either of the following, in R notation:
```
aggregate_signals(x = c(rep(list(a), 28), b), dt = c(1:28, 0))
```
or
```
aggregate_signals(x = list(a, b), dt = list(1:28, 0)
```
This should return the same thing.  But the latter is more memory efficient (I don't have to copy the entire data frame a 28 times, I just operate on the value column).

**Comment by chinandrew** [comment]
That interface looks pretty good to me. 

On the last two issues I'm in agreement with you that single geo_types and no plotting suffices for now.

**Comment by ryantibs** [comment]
Ok thanks!  I just pushed committed.  After evalcast gets merged into main, I can submit this branch for a PR to main (because I branched off of evalcast.

@capnrefsmmat @chinandrew Actually, question on general git practice: I have a bunch of stuff I'm still doing on this branch, unrelated to this `covidcast_signals()` business.  (It's uncommitted.)  I wanted to keep working on this branch for simplicity.  Should I submit this as a PR to get the work on `covidcast_signals()` merged into main (after evalcast gets merged) and then just keep working on the branch and submit a second PR when I'm ready?

**Comment by chinandrew** [comment]
If the other work is uncommitted, why not make a new branch? If it depends on evalcast stuff you can branch off of that instead of main.

**Comment by ryantibs** [comment]
It's a dependencies issue: the other stuff I'm working on depends on `covidcast_signals()` and `aggregate_signals()` etc.  And I don't want to stop working on it and only resume once that's been merged into main.

This is the same reason I branched my current branch (modeltools) off of the evalcast branch: the other stuff I'm working on depends on the evalcast packgage and I didn't want to wait until that's been merged into main.  And it not only depends on evalcast, but I'll continue to add small things to evalcast as I see a need for them.

**Comment by chinandrew** [comment]
Got it. In that case, I'd probably create a new branch off of the modeltools branch and work off that. 

In my experience it's not super common to have a feature branched from a feature branched from a feature branch, and more common to just have a bunch of features branched off of your main or develop branch (depending on your git paradigm) and frequent PRs, incremental changes, and fast reviews to keep things moving. In this example, that idealistically would look something like you submitting a <30 line PR once you're done with `apply_shifts_one()`, _maybe_ also `apply_shifts()`, tagging a reviewer who would review within a few hours (and could review it that quickly because it's only a few dozen lines), and you'd have it merged soon after and we can all move on to the next thing. Of course, we're operating under very different conditions than a bunch of full time software engineers (especially in this repo vs indicators), so we have to be a bit more creative.

**Comment by ryantibs** [comment]
Thanks for the tips.  I *think* I managed to copy the modeltools branch and name it multi-signals, and submitted that for a PR.    Will continue work on modeltools now.

**Comment by chinandrew** [comment]
:+1:

Another option, since these functions are independent of the evalcast work, is to create a new branch off main and cherry pick the relevant commits for this issue onto that branch. Then you don't run into the issue where in order to merge in your PR you need to merge evalcast.
