### ISSUE TITLE
add function that makes trajectory plots

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#101]
Given a list of predictions cards corresponding to the same forecasting task except with varying ahead and forecaster, makes a plot where one sees the actual response over a specified period and the forecast trajectories, faceted by location.  Each forecaster's trajectories are a different color (showing median).  The 100(1-alpha)% prediction interval is shown with a gray band (`geom_ribbon`).

`plot_trajectory(list_of_predictions_cards, first_day = "2020-07-01, last_day = "2020-10-01", alpha = 0.2)`.

In terms of the "actual response" referred to above, one would query from covidcast (should use evalcast's function [download_signal](https://github.com/cmu-delphi/covidcast/blob/evalcast/R-packages/evalcast/R/download_signals.R)).   The calculation of "actual" depends on the `incidence_period`... when this is `"epiweek"`, then the sum of the response over the last 7 days would be good to show.  However, when this is `"day"`, then just the raw response should be shown (this is to accommodate cumulative forecasting).

ajgreen93 and jsharpna both have code for making trajectory plots for the epiweek case... this would be a good starting point.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970313168776) by [Unito](https://www.unito.io/learn-more)

**Comment by ajgreen93** [comment]
@jacobbien @jsharpna I'd be happy to take a pass at this on Monday.

**Comment by ajgreen93** [comment]
@jacobbien @dajmcdon @jsharpna See link [here](https://github.com/cmu-delphi/covidcast/blob/evalcast-trajectory_plots/R-packages/evalcast/R/plot_trajectory.R) for a first pass at a `plot_trajectory` function. 

- Follows the conventions @jacobbien called for, except shows actual values summed to epiweeks, instead of 7 day trailing sum.
- Currently functional for `incidence_period` equal to `day` or `epiweek`, and `geo_type` equal to `county` or `state`. 
- Doesn't do any pagination, so very hard to see for many locations; can be easily fixed.
- Tried my best to properly handle function imports but can't guarantee I did it correctly.

**Comment by dajmcdon** [comment]
Thanks @ajgreen93 . I'm making some modifications at the moment (hopefully I'm the only one).

**Comment by dajmcdon** [comment]
See also #160
