### ISSUE TITLE
cache previously downloaded data

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#107]
To avoid excessive numbers of repetitive calls to covidcast (and for improved performance), we can cache data that has been downloaded by evalcast.  We just need to be sure that it's an identical query to covidcast (not just the same signal and start/end dates but also -- and this is important -- the same as_of).

To do this, one would modify [`evalcast::download_signal`](https://github.com/cmu-delphi/covidcast/blob/evalcast/R-packages/evalcast/R/download_signals.R).

This feature was suggested by jsharpna.  The person implementing this might want to talk with bnaras about how best to implement caching in R.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970444952578) by [Unito](https://www.unito.io/learn-more)

**Comment by dajmcdon** [comment]
I'll take this

**Comment by ryantibs** [comment]
@jacobbien @dajmcdon @bnaras Some comments from me, as I'm working through evalcast now ... and starting to use it for some simple analyses.

First, [this explanation](https://www.r-bloggers.com/2020/04/caching-in-r-2/) for caching options in R seems pretty helpful.  I could imagine a few ways to use `memoise()` or `mustashe()` it in the context of evalcast.

Second, let me express my enthusiasm for caching being implemented sooner than later.  As a user of evalcast 🙂 my experiments would benefit from a speedup (currently taking a while to run).

Third, even apart from caching, let me point out that a bigger deal could be to change the order of operations.  **I'm not suggesting we do this now**, but I want to point it out because it's relevant.  Maybe it's worth pursuing after caching gets implemented, as we can assign a separate issue to this.  Here goes:

Most interesting forecast analysis involve comparisons between forecasters.  Right now `get_predictions()` and `evaluate_predictions()` each only operate on **a single forecaster at a time**.  The way it's implemented now, we could easily extend `get_predictions()` or `evaluate_predictions()` so that could take multiple forecasters (would just be a simple wrapper over the current implementations).  But this would be inefficient, because if I had a lot of forecast dates, there would either be a ton of duplicated data fetching. Assuming we're always considering the same forecast dates across forecasters (the most common case I believe) ... for `get_predictions()`, there would be duplication if my forecasters used highly overlapping data sets for training, and for `evaluate_predictions()`, there would always be duplication.  

The cache won't necessarily be a perfect solution here, because if I have a lot of forecast dates I'm considering, there's a ton of caching that needs to be done, which would be memory intensive and/or itself expensive (reading/writing to disk a lot, which is how I think all the caching solutions work under the hood).

A better solution would be to reimplement a multi-forecaster version of `get_predictions()` that looks something like this: 

- for each common forecast date,
- fetch all the data needed by all the forecasters for that forecast date (here is where we could reduce a lot of duplication),
- train all the forecasters and store predictions.

You could still use caching in this setup, it would only improve things, but it's the order of operations that would help more.  And similarly, we could reimplement a multi-forecaster version of `evaluate_predictions()` that looks something like this:

- for each common forecast date,
- fetch the response data needed for all the evaluations,
- then evaluate the predictions and store the results.

**Comment by dajmcdon** [comment]
We're also looking at a package called `archivist`: http://pbiecek.github.io/archivist/.

**Comment by jacobbien** [comment]
Ok, so one proposal is to `memoise` the function `evalcast::download_signals` (and use `memoise::cache_filesystem` so this will work across R sessions).  @dajmcdon - I haven't looked into `archivist`, but it sounds like that's another option.

@ryantibs - reading about `memoise` [here](https://github.com/r-lib/memoise), it seems that by default (if one doesn't set `memoise::cache_filesystem`), then it uses an in-memory cache... in which case the reading/writing to file might not happen. 
 Ok, but I still see the advantage of your suggested changes to `get_predictions` and `evaluate_predictions` since one doesn't need to keep all the data from different forecast dates simultaneously in memory.

**Comment by benjaminysmith** [comment]
Without knowing any of the details here, I recommend doing the simplest version first and then iterating if necessary ;)

If you cache to disk, do we need to worry about not getting refreshed data? (e.g., if it is updated in between R sessions) 

It sounds like it might be simplest to cache in memory to start -- and would guess that will have immediate impact for exploratory development.

**Comment by dajmcdon** [comment]
Comparing both, my instinct is that `memoise` is easiest, and, maybe conveniently, closest to a good long term solution. Short run, we can cache to memory, and maybe move to adding a prompt or message on loading down the line.

**Comment by benjaminysmith** [comment]
Sounds convincing to me! @jacobbien what do you think?

**Comment by jacobbien** [comment]
Yes, `memoise` option to memory sounds simplest for now.  And we can re-evaluate whether @ryantibs's add-on (described above) is still a high priority after we get `memoise` cache to memory implemented.  (@ryantibs, sound good?)  Also, @ryantibs's suggestion could be moved to a separate issue.

**Comment by tildechris** [comment]
Is there HTTP-level support for caching on the API side?  Just looking through postman it doesn't look like either `Last-Modified` or `If-Modified-Since` are supported.

Adding such functionality would make it straight-forward to manage a local cache.

**Comment by capnrefsmmat** [comment]
There is not; we added compression at some point, and were going to add `Cache-Control`, but that failed because of some Apache config issues.

See https://github.com/cmu-delphi/delphi-epidata/pull/171, https://github.com/cmu-delphi/delphi-epidata/pull/191

But the API could also emit the headers directly, without Apache's help. I don't imagine many clients would be using those headers, though.

**Comment by ryantibs** [comment]
@jacobbien @dajmcdon: Sgtm.  Thanks all for the helpful replies!
