### ISSUE TITLE
data corrections within evalcast

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#112]
Incorporate the Delphi data corrections into evalcast.  This should probably always only be offered as an option that can be turned on/off rather than always being on.

dajmcdon would be the best person to do/direct this.

Data correction is relevant at various stages:

1. when predictions are made by a forecaster using `evalcast::get_predictions`
1. when predictions are being evaluated using `evalcast::evaluate_predictions`.

Both of these functions could have a flag indicating whether data corrections should be used.

One approach would be to integrate data correction directly into [`evalcast::download_signals`](https://github.com/cmu-delphi/covidcast/blob/evalcast/R-packages/evalcast/R/download_signals.R), so that whenever data is downloaded from the API, it comes with corrections (with a flag determining whether this occurs or not).

Something to consider in implementing this: An argument can be made that the "as of" principle should apply to the data corrections principle.  So in making predictions, a forecaster shouldn't have access to a correction that wouldn't have been available until a later date.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970439260183) by [Unito](https://www.unito.io/learn-more)

**Comment by dajmcdon** [comment]
Yeah, I'll take this one.

**Comment by dajmcdon** [comment]
I think this interacts with #107 . Ideally there, we want to memoise the `download_signals()` call. That will cache the api data. Then for corrections, we make them immediately after based on the flags in `get_predictions()` and `evaluate_predictions()`. We memoise those too (so they can be retrieved later if desired, say with another function).

As for the as_of, I'm not quite sure how to impose the right guardrails. In the past, corrections were little more than `dplyr::mutate()` applied to the signals, and my intention was to stay the same. Since `download_signals()` obeys `as_of`, the corrections would as well, unless the user intentionally passed a function that was based on future data. 

I'll proceed along these lines if that's ok with you.

**Comment by jacobbien** [comment]
Hi @dajmcdon.  Yes this sounds good to me.  I agree with what you said about the corrections process (as you're doing it) not violating the as of principle.  If a user is determined to break the as of guardrails, it can certainly be done in many ways... but my main concern is that the basic user using the basic functionality and options will not be led to violate this principle.
