### ISSUE TITLE
Refactor API calls to batch request multiple geo_values where appropriate

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast#121]
cmu-delphi/delphi-epidata#221 now works (docs update forthcoming), so the clients can now batch requests for multiple geo_values into a single API call.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970306664846) by [Unito](https://www.unito.io/learn-more)

**Comment by capnrefsmmat** [comment]
For reference, I think this means we can do one API call per day, regardless of the number of geo_values, instead of one per day per geo_value.

For the Python package, this will require updating [the delphi-epidata Python client](https://github.com/cmu-delphi/delphi-epidata/blob/main/src/client/delphi_epidata.py#L557) and releasing a new version on PyPI, which will require @dfarrow0.

For the R package, we can build the support right in to the package. @JedGrabman, do you feel comfortable enough with httr and the API call code in covidcast.R to take a shot at this?

**Comment by JedGrabman** [comment]
I'm not very familiar with httr, but after a quick look, I don't think I'll need to deal with it directly. This may be as simple as updating how the covidcast function within covidcast.R handles the geovalue parameter. Go ahead and add me as an assignee and I'll work on the R package portion.

**Comment by capnrefsmmat** [comment]
Yeah, I think you'll just have to make it look more like how the `issues` parameter is handled, using the helper functions that are already there.
