### ISSUE TITLE
Comprehensive testing for packages

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#124]
Sarah C. suggested that it would be helpful to have tests based on a mini data set.

David F. mentioned: "it's possible to spin up a local instance of the epidata api inside of a docker containr, and tests would just need to point at that rather than the actual api
"

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970305385997) by [Unito](https://www.unito.io/learn-more)

**Comment by ryantibs** [comment]
@jacobbien I hijacked this issue!  Hope that's ok. ;) 

This issue should be made more broad: we should implement comprehensive unit tests for our packages, to make sure that each time we update them, we don't break existing functionality.  This is easy to do in R with the `testthat` package (and nicely integrates into package development).  I'm sure Python has good functionality too.  

Despite the fact that we [teach about this being good practice](http://www.stat.cmu.edu/~ryantibs/statcomp/lectures/debugging.html), so far we've done very little testing.  And we've mostly relied on rerunning the vignettes (or example notebooks) to convince ourselves that new things "work as expected", and old things "still work".  But this should be formalized.   

(The most recent example of an update to `county_geo` in `covidcast` that broke `evalcast` highlights that the dependencies are going to grow complex, and we need comprehensive testing.)

I'm sure @bnaras @undefx know more about this than me.  Maybe this could be a project for @bnaras with help from one or two of @sarah-colq @JedGrabman @nmdefries @chinandrew?  cc @capnrefsmmat 

p.s. I know it's hard(er) to test statistical functionality, but we can always at least test against what we were doing in previous versions of the packages.  In R you can use `devtools::install_github()` and specify a commit number, to rewind the clock on what the package was doing.

**Comment by chinandrew** [comment]
Don't have a ton of background on evalcast (or the R client at a low level), and have not unit tested R before, but few notes:

- Looks like there's some [mocking](https://github.com/r-lib/mockery) functionality for R, which might be usable for the API. The Python tests mock out all networks calls this way.
- Testing _might_ will tell you when things break, but dependency management goes beyond that to making sure things don't break in the first place and devs are aware of their design implications. If I change `county_geo` in `covidcast` but and update my tests accordingly, all the `covidcast` tests may pass and I think I'm good to go. I don't run the `evalcast` tests since that's a different package, and I break something. This gets even worse the further upstream you go, like changing the epidata API. This challenge is an unfortunate consequence of splitting up your services (vs a monorepo), and I don't have great solutions. 
- I don't always do this because I get lazy, and it isn't really applicable when testing after code is written, but I'll mention [TDD](https://en.wikipedia.org/wiki/Test-driven_development) as an optional strategy going forward. tl;dr you write tests _before_ you implement the code.
- If anyone knows how to easily test complex images across platforms, let me know. @capnrefsmmat and I ran into a lot of issues with different rendering engines and never found satisfactory answers. For now the Python package just does RGB value comparison on Linux only (which is what the CI system runs).

**Comment by JedGrabman** [comment]
A few comments:
* Mocks are not my area of expertise, but in my experience some of the major benefits are that they are consistent, fast and don't need to call into external services. However, I find that there can be a fairly significant cost to using mocks, since you need to ensure:
  * they stay up to date with how the dependencies actually function and 
  * that they don't hide errors in low level changes that have been mocked out higher up the call stack.  

  If the speed or network/db impact of tests are not a major concern, I might suggest that CI would be more beneficial at this point.

* for covidcast vs. evalcast dependencies, I think it will lead to greater long term stability if we treat them as though they should be self-contained where possible. While we should strive to have a good understanding of dependencies, reducing the number and complexity of these dependencies will be beneficial (particularly for any open source volunteers who would not expect them). For the `county_geo` example, evalcast was relying on an internal implementation detail of covidcast. To prevent the issue from recurring, I would recommend either covidcast should have an externally visible way to retrieve the data that abstracts away the implementation details, or evalcast should handle retrieving the necessary data by itself. Keeping the responsibilities of each package clear will help.

**Comment by capnrefsmmat** [comment]
Closing this issue because both packages now have tests, and if we need additional tests, we should make more detailed issues for specific missing tests.
