### ISSUE TITLE
Ensure all exported functions are documented thoroughly

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#226]
Also, need examples.

**Comment by ryantibs** [comment]
I think the documentation is pretty good at this point (since I took a full pass over it in my review), but maybe things are still missing?  

Also, just to mention: as long as we have a good vignette (or multiple good vignettes) with plenty of examples, we don't need lots of examples in the package.  We can always refer them, in the documentation, to look at the vignette.  This is the approach we took in the covidcast package for most of the "complicated " functions.
