### ISSUE TITLE
msg` has been renamed to `message` 

### ISSUE THREAD

**Issue by gtzwang** [cmu-delphi/covidcast#251]
Hi, I just installed covidcast package. Getting this error. Any idea what that means? Thanks!

> covidcast_signal(data_source = "fb-survey", signal = "smoothed_cli", start_day = "2020-05-01", end_day = "2020-05-07",geo_type = "county")
Fetched day 2020-05-01: 1, success, num_entries = 1052

Error: `msg` has been renamed to `message` and is deprecated as of rlang 0.3.0

**Comment by capnrefsmmat** [comment]
Ah -- it looks like this is a consequence of #151 and a change in `rlang`.

Specifically, this warning: https://github.com/cmu-delphi/covidcast/blob/9bf67daf59926879289eaff22b585023597e2eba/R-packages/covidcast/R/covidcast.R#L502-L516

When `geo_values = "*"`, the default, this incorrectly issues a warning, because `"*"` just means "all available". And since we include an argument named `msg`, `rlang` complains that is deprecated, even though we're not using it to mean a message (just to store the error message from the API).

@JedGrabman, since this came from #151, could you fix the geo check to not check for missing geos when requesting `"*"`, and change the name of the argument to the warning?

Then we should add this warning to our list of tests to implement in #239, so the tests would have caught this issue. Sorry I didn't see it in review.

**Comment by JedGrabman** [comment]
Fix seems simple enough, opened a PR.
As a side note from testing, we seem to allow searches for vectors with "*" in them, which searches for the literal (i.e. You can set `geo_values = c("AK", "*")` which only returns results for Alaska). I matched the behavior with the warning (e.g. `Data not fetched for some geographies on 2020-05-01: * `) and I think the behavior is reasonable for covidcast_signal (although maybe a warning is warranted), but it seemed like an edge case worth mentioning.

**Comment by capnrefsmmat** [comment]
Closing this as fixed by #252.
