### ISSUE TITLE
`location_to_be_forecast` deprecated in evalcast?

### ISSUE THREAD

**Issue by capolitsch** [cmu-delphi/covidcast#268]
I'm iterating through errors in my migration of aardvark from evalforecast to evalcast, so I may be opening a number of issues...

evalforecast used to add rows to the `variable_name` column of the upstream df called `location_to_be_forecast` which would then allow us to filter our training data in modeling. It seems the `variable_name` column, as well as the `n_locations` argument, is now deprecated in favor of `geo_values` with all (`*`) being the default. This is an easy enough modification but the evalcast df does not contain a `geo_values` column (only `location`). I could of course hardcode in the matching between `location` and `geo_values` but it would be helpful if `geo_values` already existed in `df`.

Below is a code chunk from aardvark (with evalforecast dependency). The second step is where I need to be able to filter on `location_to_be_forecast`/`geo_values` for training.

```
    # (1) Don't use any data past the last_train_date
    df_train <- df %>%
      filter((is.na(issue) & 
                (time_value <= forecast_date)) | issue <= forecast_date | is.na(time_value))
    
    # (2) Concentrate on the locations we need.
    stopifnot("location_to_be_forecast" %in% unique(df_train %>% pull(variable_name)))
    forecast_locations <- df_train %>% 
      filter(variable_name == "location_to_be_forecast" & value == 1) %>%
      pull(location)
    df_train <- filter(df_train, location %in% forecast_locations)
```

**Comment by jacobbien** [comment]
You're right this is a difference from how `evalforecast` works.  For evalcast, I didn’t want to include the "locations to be forecast" functionality from `evalforecast` because I think that's too complicated and would scare potential users away.  Instead, an individual forecaster can internally decide which locations to make forecasts on.

Now, you can correct me if I'm wrong, but in the case of aardvark, I don't think this logic is even used.  Doesn't it always just forecast all 50 states + PR?  (This will, however, be relevant for the county-level forecaster I believe.)

**Comment by capolitsch** [comment]
Thanks for the clarification! Aardvark did indeed previously use this logic (see above code chunk) but I will go ahead and factor it out.

**Comment by jacobbien** [comment]
Right, well it had to use this logic because of evalforecast, but what I meant to say is that it didn't _need_ this logic to accomplish its goal...

**Comment by jacobbien** [comment]
Also: Issue #272 will clarify the documentation about the location vs. geo_value question you raise above.  Thanks!
