### ISSUE TITLE
Refactor signal correlations notebook (and app?)

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/covidcast#31]
The correlation-utils branch (soon-to-be-merged, I believe) includes correlation functionality right in the R package.  This will make computing correlations for our own purposes much easier and clean.  The `covidcast_cor()` function is the place to look: it allows us to

* choose whether we slice by time, or slice by geo location, before computing correlations
* specify an arbitrary lag (or lead) for each of the signals before computing correlations.

The correlation vignette gives lots of examples of this.

We should refactor the signal correlations notebook (and I'm guessing also the correlations shiny app?) so that it uses the package functionality.  This will make the code cleaner and allow us to do more powerful correlation analyses; for example, the signal correlations notebook only looks at correlations over one week.  With the package functionality, it's very easy to extend this to all time.

One thing to note: the signal correlations notebook (and the correlations shiny app, I think by inheritance) looks at "sweep cuts" of counties by population.  This made the correlations look better (bigger counties, better correlations).  This isn't something that I implemented in the `covidcast_cor()` function because I think it was actually just a proxy for screening out counties where there was hardly any COVID activity before computing correlations.  Now I suggest just screening out counties with less than (say) 500 total COVID cases before computing correlations; again the vignette gives examples of this. 

Tagging krivard capnrefsmmat jsharpna because they might have ideas of who could tackle this.  It's relatively low priority but would be a good way for somebody to onboard themselves both with respect to getting to know our R client and our signals.  Also tagging nloliveira huisaddison in case they're interested.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970322867642) by [Unito](https://www.unito.io/learn-more)

**Comment by ryantibs** [comment]
I just refactored our signal correlations notebook to use the package code.  See [here](https://cmu-delphi.github.io/covidcast/R-notebooks/signal_correlations.html) for convenience.

@jsharpna @krivard @mariajahja @rumackaaron This exposes that the doctor visits signal correlations have been dropping at the county level now, for a while.  (I showed a static plot of this to James earlier today.).  And the combo indicator looks to be affected accordingly.  Metro area don't look as bad.  Let's follow-up on the covidcast-indicators repo with an issue?

And, this serves as more evidence that we should just auto-run this correlation notebook, as well the "dashboard" notebooks like the one I created for the Facebook survey [here](https://cmu-delphi.github.io/covidcast/R-notebooks/fb_dashboard.html).  Set it to run at some time each day right after all the signals have been updated (after the combo indicator has been updated?) and assign each person to look at each notebook we're maintaining.  @krivard I assume we have a way to set this up (a better way that just cron jobs)?

**Comment by krivard** [comment]
In principle, yes, we absolutely should auto-run these and monitor system status. There are two moving parts of that system: How should they be run, and who should monitor them?

For how to run them: **I would recommend running them with cron for now, on some machine other than the primary delphi server.** In theory we could run them using Delphi Automation. However, so much of what Delphi produces is run through that single system that it is now becoming a liability. For example, each time we make a major modification to the API server, we have to take Automation offline -- along with all the jobs that depend on it -- so that Automation doesn't surprise us by trying to access the database while we're working on it. `cron` is a little more robust because it (1) comes for free with the OS (Automation is gnarly to install and has a lot of dependencies) and (2) each job is truly independent, but it sounds like you have reservations about using it. @korlaxxalrok I believe has some nascent plans for moving us off Delphi Automation and onto a COTS system, but further research on that would require breathing space that we just don't have right now, and we won't have it until we clear the current performance fix, the survey data challenge event, and the problems with the diff-based issue definition system in JHU. 

For who should monitor output: **I don't know what to do about this problem, and would welcome any suggestions you might have.** The complication stems from the combination of workload and understaffing. A notebook for each data source is 9 notebooks so far, +1 if you split indicator-combination into nmf and cases/deaths, +1 if you split quidel covid from quidel flu. That's either 9-11 people each monitoring one notebook every day, or one person monitoring 9-11 notebooks every day. As we transition into fall, we're slated to lose a ton of staff, and 9-11 people is a lot; if we instead assigned it to a single person we'd have to set up a rotation because 9-11 notebooks is a lot to digest if we want them to do it carefully. The 9-11 figure is additionally not fixed: there are :counts: 10 more data sources we want to add which are already on the list, not counting any sources the data partnerships team is currently working to secure.

**Comment by ryantibs** [comment]
Thanks @krivard for the detailed reply!  And thanks for the explanation about the difficulties of automation and competing priorities.  Quick response:

- I'm not at all opposed to cron for now, if that's the most sensible immediate solution (which it sounds like it is). Is this something you or Brian can easily set up, just straight from the Rmd's that exist in this GitHub repo?

- Monitoring output: I have an idea on how to simplify the problem, which is to focus for now on 4 dashboards: a dashboard for the FB signals, a dashboard for doctor visits and hospital admissions (together), a dashboard for the combo indicator (NMF), and a dashboard for cases and deaths (together). Might it be better or more efficient to discuss the rationale on a call? Let me know.

**Comment by ryantibs** [comment]
@krivard @jsharpna I just reorganized a bit.  The R notebooks are now in the covidcast/R-notebooks directory.  The knitted html files are still in covidcast/docs/R-notebooks, so that you can still see them through GitHub docs [here](https://cmu-delphi.github.io/covidcast/R-notebooks/fb_dashboard.html) and [here](https://cmu-delphi.github.io/covidcast/R-notebooks/signal_correlations.html).

James: you guys can work directly in the R notebooks directory (on a branch).  

Katie: I added a makefile in the covidcast/R-notebooks directory called "make.R".  You can call it from the command line using 
```
R --vanilla < make.R
```
It'll knit into html whatever Rmd files it finds in covidcast/R-notebooks.  It's not the smartest makefile, but it's not the dumbest either (it should catch errors, print error messages to the console, and then proceed onto the next notebook, rather than crash if there's any error in any notebook).

Currently I'm just manually copying them over to covidcast/docs/R-notebooks, but we can stop doing that whenever you set this up say a cron job and hang the html files off of, say, www.delphi.cmu.edu (if we can), or somewhere else convenient.

**Comment by ryantibs** [comment]
@krivard Any updates on setting up the cron job?  As a temporary solution, should I do it on my own stats site (http://www.stat.cmu.edu/~ryantibs)?  Doesn't look hard for me to set up. 

And can you remind me, what is the more permanent solution here?  Are we going to hang these off the Delphi website, or somewhere else?

**Comment by krivard** [comment]
Thanks for the ping, I missed your previous comment. I will set up a cron
job today in a sample space. Once it’s working we can hang it wherever we
like, either off the main Delphi website or off the COVIDcast site once we
migrate away from CMS.

**Comment by krivard** [comment]
https://delphi.midas.cs.cmu.edu/~krivard/covidcast/

**Comment by ryantibs** [comment]
Thank you!  Lgtm.

@zackchase Can you think about where this should live in the scheme of the new Delphi website.

**Comment by ryantibs** [comment]
@krivard I'm going to close this issue, which was originally about correlations.  I refactored the notebook a long time ago to used `covidcast_cor()`.  We can pick up the convo on dashboards on the other one #32.   

As far as I know, the shiny app still doesn't use `covidcast_cor()`, but it's not currently being actively used anyway.  (Is it?).  Just pinging @nloliveira one last time before I close this issue for good.  It's not at all a priority and fine if we leave it, but the shiny app is going to basically grow stale unless we hook it up to the covidcast package, which will be the stable place to compute correlations from now on.
