### ISSUE TITLE
Add Ryan's `canonical_plot()` function to evalcast

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#410]
See his PR #398. 

- [x] Move `modeltools::canonical_plot()` to evalcast. 
- [x] Ensure its setup/documentation matches the evalcast structure as necessary.
- [ ] Add figs from the modeltools demonstration to a new vignette in evalcast.

**Comment by JedGrabman** [comment]
I'll wait on #417 to be closed, since `canonical_plot` depends on `scale_by_forecaster`.

Should `canonical_plot` be publicly available? Or should we just use it in the background to standardize how our other plots look?

And I guess as a larger scale question, is `modeltools` a package that we (being Delphi) are going to maintain? If so, it seems that we should just have one copy of `canonical_plot`, so if it lives in `modeltools`, we should consider just pulling it in from there.

**Comment by dajmcdon** [comment]
`modeltools` is maintained by Delphi. It doesn't have `canonical_plot` in it. 

Yes the intention is to make it available.
