### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [cmu-delphi/covidcast#597]
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that this is due to changes in the warnings and errors thrown by ggplot2 that you test for in your package

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by capnrefsmmat** [comment]
Thanks for the notice. It looks like the warnings are due to our use of `aes_string()`, which is now deprecated. We used `aes_string()` because it was previously recommended as a solution for check NOTEs about use of variables without visible bindings. What's the preferred solution now?

The current documentation for `aes()` is a little vague. It refers to the [Programming with dplyr](https://dplyr.tidyverse.org/articles/programming.html) vignette for tidy evaluation idioms, but doesn't specifically say if `aes()` is using data masking or tidy selection. I assume it's data masking, given the ability to write arbitrary expressions. In that case, is the right approach to write things like `aes(x = .data$foo, y = .data$bar)`?

**Comment by thomasp85** [comment]
Indeed, `aes()` is a case of data masking. You can either use it as you would interactively, i.e. `ggplot2::aes(geometry=geometry)` and set `geometry` as a global variable using the `globalVariable()` function (which exists to suppress the notes), or you can use the `.data$` prefix as you have suggested. Either is fine
