### ISSUE TITLE
Handle both standard and non-standard column orders of CovidHub forecast files in `get_covidhub_predictions_alt`

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/covidcast#609]
`arrow` version 4.0.1 _reorders_ columns to match the provided schema. Newer versions require that all csvs have columns in the same order as each other and as the schema.

This is a problem for forecasts from CovidHub. About 25% of forecast files use a non-standard column ordering. Files for different submission dates can use different orders even within the same forecaster.

The issue with different column ordering needs to be resolved in an efficient way before we can start using `arrow` 10.0.1.

https://github.com/cmu-delphi/covidcast/pull/607 offers an inefficient solution. It reads the header for every downloaded forecast file. If the header order disagrees from the standard order, the entire file is read in, columns reordered, and rewritten to disk. What with the reading and re-writing and re-reading again later (on the actual read by `arrow`), this isn't fast especially since a large proportion of files use non-standard column orders.

[Supports newer `arrow` versions](https://github.com/cmu-delphi/covidcast-docker/issues/14).

**Comment by nmdefries** [comment]
Alternate proposal deprecating `arrow` entirely:

Fetch forecast files directly into memory with `data.table::fread`, which can read from urls. This is faster than downloading to disk with `arrow` by 4x but uses 50% more memory, although this particular spot in the code isn't memory-limited.

Haven't tested the speed of splitting the `target` column in the `arrow` vs `data.table` approaches.

**Comment by brookslogan** [comment]
Two cents: I don't think we're taking advantage of `arrow` much, because we immediately `collect` the dataset into a data frame / tibble in RAM, and `arrow` adds significant install time.  I would suspect there'd be an R library that can already do that just as fast.  `data.table::fread` and `readr::read_csv`.  Whether they directly support reading from URLs doesn't seem like a determining factor; like I believe we already do with `_alt` (with `arrow`), we could download to a file, then read that file.
