### ISSUE TITLE
plot_calibration gives .data errors, based on type of plot, when following evalcast tutorial

### ISSUE THREAD

**Issue by zterner-mitre** [cmu-delphi/covidcast#640]
I am trying to replicate the tutorial found at https://cmu-delphi.github.io/covidcast/evalcastR/articles/evalcast.html on my local machine. Things generally work (thanks Dmitry!) up until `plot_calibration`.

The first instance of `plot_calibration` is giving this issue, which occurs in `format_wedgeplot`, but refers to subsetting .data outside of a data mask context.
<img width="651" alt="image" src="https://github.com/cmu-delphi/covidcast/assets/117375468/ff23d87b-7d19-4b68-bef3-f0550dd0ec43">

The second instance gives an identical issue and traceback to the first.

The third instance gives a similar subsetting .data issue, but says it occurs in `format_traditional_calib_plot`.
<img width="722" alt="image" src="https://github.com/cmu-delphi/covidcast/assets/117375468/43cc63eb-cfe1-437b-bca6-649aeed0d44b">

Are there packages on my end that I am missing and need to install/update?

**Comment by dshemetov** [comment]
Can reproduce. Taking a look into this...

**Comment by brookslogan** [comment]
This error is due to a newer version of `rlang` or maybe `dplyr` catching a pre-existing bug in the evalcast plotting code.  Quick patches would be:
- Cloning this repo, and commenting out both uses of `labs` (or just the title setting) in R-packages/evalcast/R/plot_calibration.R, `devtools::load_all()`.
- Downgrading `rlang`.

fad379fa8b0e2f76ecc4484f7d6425bcca09dbb7 introduced the `.data$` part of this, maybe because a package check was warning about this same bug.  But actually/now, it was just getting `NULL` for `.data$name` etc. and that made things run on old `rlang`/`dplyr`.  Prior to this commit, I'd guess we somehow had global variables `name` and `ahead` set someplace (maybe in the vignette), but don't have them anymore.

Fixes on our side: we could remove the `title =` part or try to correct it to what it was meant to produce.
