### ISSUE TITLE
Follow-up to issue #655: incident cases also give odd metrics

### ISSUE THREAD

**Issue by zterner-mitre** [cmu-delphi/covidcast#656]
Hi,

Following up on this issue (https://github.com/cmu-delphi/covidcast/issues/655), I wanted to provide code and show similar issues we are experiencing in comparing incident cases in early 2022. 

I am attaching two files to this issue. One is a reproducible code example that will demonstrate the issue.
[reproducible2-ex-evalcast-inc-jan2022-as-txt.txt](https://github.com/cmu-delphi/covidcast/files/12373660/reproducible2-ex-evalcast-inc-jan2022-as-txt.txt)

The second is a file of predictions that we are trying to compare against predictions made by the ForecastHub teams. The code pulls in this file easily -- hopefully it works without much issue. The file is set up to be in the same format as the prediction cards so that everything row binds together easily.
[example-predictions.csv](https://github.com/cmu-delphi/covidcast/files/12373664/example-predictions.csv)

In the code file, I am downloading incident case data for the omicron wave (Jan 2022), binding the example predictions file to it, and trying to score the forecasts using WIS, AE, etc. We are finding that although the example code file gives worse predictions - it predicts about 10k cases per day when it should be about 70k - it performs better on WIS, AE, etc.

One thought I had is that the the incidence period may be what's driving this, since incidence period is set to "day" for the example file and "epiweek" on the CovidHub. I tried to download incidence period = day data from CovidHub, but I think it didn't work / didn't return it when it should've since I didn't specify incidence_period in the function call. I also tried changing incidence period in the example file to "epiweek" , but that didn't change much in the output.

Is incidence period the problem here, and if so, how would one address it? Or is this a similar issue to the cumulative WIS calculation from Issue 655? All these forecasts are incident so I am not sure if that could be the issue. 

Additionally, the package pulls down different "Actual" data for the example forecast and the CovidHub forecasts, but I am not sure why. (This is highlighted at the end of the code.) Perhaps this is related to the issue that was noted in 655?

Thanks,
Zach

**Comment by nmdefries** [comment]
> I also tried changing incidence period in the example file to "epiweek" , but that didn't change much in the output.

Besides changing the `incidence_period`, you also have to change the `aheads` so they're measured in units of weeks. Otherwise, the `example` forecasts are scored against truth data 20 _weeks_ in the future; those values will be totally unrelated to the forecasts and will create bogus scores. I ran:

```
example_forecasts <- read_csv("example-predictions.csv") %>%
  # Remove row number column
  select(-`...1`) %>%
  # Keep only rows corresponding to full-week aheads (so 7 days, 14 days, etc ahead)
  filter(ahead %% 7 == 0) %>%
  # Convert "days ahead" to "weeks ahead", and set incidence_period to `epiweek`
  mutate(ahead = ahead / 7, incidence_period = "epiweek")
```

Once we're pretending that the `example` forecasts are on a weekly basis, they perform a lot worse compared to the other models:
![Looking at WIS](https://github.com/cmu-delphi/covidcast/assets/42820733/5e1075b3-aab0-4a6f-9499-41df827f0092) (plot for AE looks similar)

Looking at predictions and scores for early Jan (`target_end_dates` for CovidHub models and the `example` forecaster don't match exactly because of the day -> epiweek conversion and daily aheads aren't required to line up with week boundaries),  we see that the `example` forecast was way way low compared to the actual value (~540k). Some of the other forecasters were in the right ballpark, so `example` performs poorly.
![Predictions and scores for early Jan](https://github.com/cmu-delphi/covidcast/assets/42820733/dd3d740d-8e71-4d00-9c68-8251833f1392)

Looking at predictions and scores for late Jan, we see that the predictions are around the same values as they were in early Jan, but the actual value is now much lower (~115k), but . So the `example` forecast is now much more reasonable (-100k, but there are also forecasts that are +100k of actual) and compares favorably.
![Predictions and scores for late Jan](https://github.com/cmu-delphi/covidcast/assets/42820733/75610203-7b02-49ab-aafb-568e11adddc6)

**Comment by nmdefries** [comment]
To be able to compare to the Hub forecasters, you'll need to make sure that your forecaster is predicting the same target.

The CovidHub has [info about the targets they support](https://github.com/reichlab/covid19-forecast-hub/tree/master/data-processed#target) -- it looks like `N days ahead incidence cases` was never officially accepted, so you won't be able to compare your predictions as-is to any in the Forecast Hub.

My recommendation would be to switch to predicting weekly instead of daily values. I suppose to get an idea of your current performance you could sum your daily predictions over a week, but I wouldn't use that in a formal analysis. I doubt the statistical validity of summing prediction quantiles.

As an aside, for formal comparisons, you'll also want to separate predictions by ahead. The farther out you try to predict the worse the accuracy, so it's not very meaningful to compare 1-week aheads with 4-week aheads. I realize this is a toy example and there aren't enough aheads for all forecasters in your script to do this, but something to consider in your real analysis.

**Comment by nmdefries** [comment]
>  I tried to download incidence period = day data from CovidHub, but I think it didn't work / didn't return it when it should've

If you're still interested in doing this, please send a code snippet with what you tried. I'm having trouble understanding what you did; I think I don't have enough context here to make any suggestions yet.

**Comment by nmdefries** [comment]
@zterner-mitre Wanted to be sure you saw this. Does this make sense? Any follow-up questions?

**Comment by zterner-mitre** [comment]
@nmdefries Thanks! All of the above makes complete sense. I wrote some code to sum up daily incidence projections for each quantile over a week to get a rough sense of how the forecasts compare -- they compare well, but I also doubt/question the statistical validity of that exercise. (I personally think the sum of the point estimates might approximate the point estimate of the sum with enough data/time, but that's just my intuition and would need a formal proof or examination of it.)

Regarding the snippet you quoted about "incidence period = day": I meant that in my call to `get_covidhub_predictions`, I didn't specify `incidence_period`, so I was hoping it would return both data for `incidence_period=epiweek` and `incidence_period=day`, since the default in the function is to do both. Of course, it can't return data for `day` if it's not available in the forecasters' submissions (for incident cases), so it just gave them to me for epiweek.

Thanks for all your help!

**Comment by nmdefries** [comment]
Great, glad that was helpful. I'm going to close this as resolved, but please reach out in the future if you have any additional questions or issues!
