### ISSUE TITLE
Error when fetching metadata from the API

### ISSUE THREAD

**Issue by lematt1991** [cmu-delphi/covidcast#87]
I'm currently seeing the following error:

```
RuntimeError: ('Error when fetching metadata from the API', 'error: Expecting value: line 1 column 1 (char 0)')
```

When getting metadata:

```Python
>>> import covidcast
>>> covidcast.metadata()
```

**Comment by capnrefsmmat** [comment]
Works for me here. Do you know what version of the package you have installed? You can find out with `pip show covidcast`.

It's possible that you have an older version that points at delphi.cmu.edu instead of api.covidcast.cmu.edu. The delphi.cmu.edu endpoint can be very slow or fail to return responses when major database operations are occurring.

**Comment by lematt1991** [comment]
Ah that was it, thanks for the quick reply!  `pip show covidcast` gave:

```
Name: covidcast
Version: 0.0.8
Summary: Access COVID-19 data through the Delphi COVIDcast API
Home-page: https://cmu-delphi.github.io/covidcast/covidcast-py/html/
Author: Alex Reinhart
Author-email: areinhar@stat.cmu.edu
License: UNKNOWN
Location: ...
Requires: requests, delphi-epidata, pandas
Required-by:
```

`pip install --upgrade covidcast` brought me up to 0.0.9 which works.  Thanks!
