### ISSUE TITLE
Cut a new Python client release

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#90]
- [x] Update changelog to describe changes since 0.0.9
- [x] Rebuild all documentation and proofread for typos
- [x] Change version number in setup.py and the Sphinx config file
- [x] Build new package dists
- [x] Upload to PyPI
- [ ] Announce to API mailing list

@chinandrew, any changes we need to make before we should release 0.0.10? Should we celebrate by calling it 0.1.0?

**Comment by chinandrew** [comment]
I'll take a look tomorrow on any last items. In terms of release numbering,
have we been using any specific system or just incrementing up? Depending
on how formal we want to be, would suggest something like semantic
versioning (https://semver.org), potentially modified where needed. In that
model, incrementing minor version makes sense. It also states we
technically should be on major version 1 since it's public, but that's
something we could ignore if it'll be confusing to change now.

**Comment by capnrefsmmat** [comment]
I'm happy to use SemVer. I think it lets us do anything we want when we're still 0.x.y, so that leaves us the question of when we're ready to declare our public API stable and release 1.0.0. I'm thinking that should wait until we have some more users, and feedback from those users, so we know our design decisions are solid.

**Comment by chinandrew** [comment]
Oops accidentally had this closed, but there's still open tasks. Reopened.

**Comment by chinandrew** [comment]
@capnrefsmmat are the last 3 things that you have to do since you have the pypi account?

**Comment by capnrefsmmat** [comment]
Yep. I'll check out the docs, then do the PyPI release.
